### ISSUE TITLE
Documentation for Previous version

### ISSUE THREAD

**Issue by dev-thinks** [primefaces/primeflex#87] opened 2021-11-28 21:02 UTC
Hello,

As the latest version V3 is having more breaking changes in most of the classes. Is it a good idea to keep the documentation of flex for version 2.X as well ?

For some time, we are planning to keep 2.X as we are recently migrated from previous breaking changes with primeng.

please let me know where to get the documentation of version 2.X. Thank you.

**Comment by melloware** [comment] 2021-11-29 12:20
Duplicate of: https://github.com/primefaces/primeflex/issues/61

**Closed** 2021-12-07 18:07 UTC
