### ISSUE TITLE
Doesn't work with basic usage (includes used workaround)

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeflex#8] opened 2019-01-03 17:32 UTC
I've created a simple project with angular-cli, includes the dependency and updated the angular.json. After this, I've used the grid as the example below:

```
<div class="p-grid">
    <div class="p-col-2">2</div>
    <div class="p-col-6">6</div>
    <div class="p-col-4">4</div>
</div>
```
The number 4 was expecting to be at the same line than the other, but it didn't happen.

It only worked after using this CSS rule in my styles.css:

```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

**Comment by nils-christian** [comment] 2019-03-19 10:33
I can confirm this. This even happens without angular or something. A plain html site only with primeflex.css has the same issue. 
```
<!DOCTYPE html>
<html>

	<head>
		<link rel="stylesheet" type="text/css" href="primeflex.css">
	</head>

	<body>
		<div class="p-grid">
			<div class="p-col-2">2</div>
			<div class="p-col-6">6</div>
			<div class="p-col-4">4</div>
		</div>
	</body>

</html>
```

In this case the "4" can be found in the next line.

**Comment by TheRealOha** [comment] 2019-08-07 14:23
Still an issue. Please fix this. 
**This is utterly annoying especially since the former PrimeNG Grid (ui-g) has been declared deprecated and Flexgrid is explicitly given as alternative**.
The new line wrap starts after you have filled 11 rows, instead of 12.
Given:
<div class="p-grid">
  <div class="p-col-6">6</div>
  <div class="p-col-6">6</div> 
  <div class="p-col-6">6</div> 
  <div class="p-col-5">5</div>
</div>
Result:
6
6
6                              5
According to documentation it should be:
6                              6
6                              5
Example see: https://stackblitz.com/edit/primeflex-grid-off-by-1?file=src/app/app.component.html

**Comment by mertsincan** [comment] 2019-10-09 07:20
Thanks a lot for the sample codes. Fixed now.
```
.p-grid > .p-col,
.p-grid > [class*="p-col"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box; }
```

**Closed** 2019-10-09 07:20 UTC
Labels: bug
