### ISSUE TITLE
Form Layout Issue

### ISSUE THREAD

**Issue by joshua-kissinger** [primefaces/primeflex#97] opened 2022-02-04 20:50 UTC
It seems like styles from this [sheet ](https://primefaces.org/primeflex/assets/css/styles.css) are used extensively on [this ](https://www.primefaces.org/primeflex/formlayout )page to make the form layout look good, but I can't find that it is part of the distributed code in any version of primeflex 3.x. I followed the set-up instructions and most stuff in the primeflex library works, but the form layout examples do not look right. Another person pointed out this issue on [SO](https://stackoverflow.com/questions/69201710/primeflex-3-and-angular-12-unable-to-render).

**Comment by melloware** [comment] 2022-02-04 20:55
That styles.css is custom for that showcase.  If you need it just copy it. Its not part of PrimeFlex

**Comment by secorguy** [comment] 2022-02-04 21:12
Thank you for the reply. It seems like that would be more clear if the classes that are part of PrimeFlex were separated from those that are not. This particular set of sample code appears to have more non-library classes than those included in PrimeFlex. From my experience using PrimeNg and other UI libraries, one can copy sample code and generally expect it to look the same as the sample assuming everything is setup correctly and the same theme is applied. Thanks for your work on the library though, very useful.

**Comment by melloware** [comment] 2022-02-04 21:14
Hopefully PrimeTek will read this.  I do know what you mean about copying and pasting samples and expecting them to work.

**Comment by AlexPash-ceo** [comment] 2022-03-04 16:56
Hello, please take a look at [this issue](https://stackoverflow.com/questions/69201710/primeflex-3-and-angular-12-unable-to-render). I've encountered the same and can't figure out how to apply the PrimeNG theme styles to the form. I'm just learning Angular and can't find the cause of this issue. I don't want to fall back to PrimeFlex 2 and then migrate. I want it to work like primeflex 2, so please tell me how to make the theme and styles that I use in primeng also apply to the form grid. Thanks to.

**Comment by mertsincan** [comment] 2022-04-25 23:32
Fixed now! Thanks a lot for your report!

**Closed** 2022-04-25 23:32 UTC
